In [1]:
import numpy as np
import random

In [2]:
it = [1,3,5,7,11]

In [5]:
n = np.array(it)

In [6]:
type(n)

numpy.ndarray

In [7]:
twod = np.array([[1,2],[3,4]])
twod

array([[1, 2],
       [3, 4]])

In [8]:
twod = np.array([[1,2],[3,4,5]])
twod  # There is unequal elements in both array so it make it as list

C:\Users\IT\AppData\Local\Temp\ipykernel_12364\3959930743.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  twod = np.array([[1,2],[3,4,5]])


array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [14]:
y = np.array([1,2,3,'4'])

y # this array becaome in U11 code as it convert every integeri into string
# y.shape
# y.size

4

In [19]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
list(range(9,20,2))  # this gives us range from 9-20 with gap of 2

[9, 11, 13, 15, 17, 19]

In [25]:
# np.arange?     To find documentation of that function




In [53]:
arr1 = np.arange(40)


In [27]:
arr2 = arr1.reshape(8,5)


In [28]:
arr1[0] = 1000
arr1

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39])

In [29]:
arr2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [51]:
# Broadcasting in numpy

a  = np.random.randint(1,100,[2,4])  #these works
b  = np.random.randint(1,100,[2,4])

# a  = np.random.randint(1,100,[4])   this also works
# b  = np.random.randint(1,100,[2,4])


# a  = np.random.randint(1,100,[4,2]) This don't work
# b  = np.random.randint(1,100,[2,4])

# a  = np.random.randint(1,100,[23,32,1,2,4])  This also work 1 in it
# b  = np.random.randint(1,100,[2,4])

# Rules:- 1) Shape should be same check from right to left
# 2) If it has 1 in it will work

In [52]:
a+b

array([[168,  95, 120, 108],
       [127, 102,  93, 110]])

In [34]:
b

array([[25, 82, 40, 73],
       [86,  8, 23, 83]])

In [35]:
a

array([66, 15, 29, 35])

In [58]:
data = np.random.randint(1,10, size=(2,3,4,5,6))
data

array([[[[[7, 5, 7, 9, 7, 7],
          [4, 2, 8, 6, 6, 4],
          [6, 3, 1, 6, 1, 7],
          [2, 4, 1, 5, 9, 6],
          [1, 5, 1, 3, 2, 6]],

         [[4, 6, 1, 1, 5, 1],
          [9, 9, 9, 5, 3, 8],
          [2, 3, 1, 7, 2, 5],
          [4, 5, 1, 8, 1, 1],
          [5, 8, 7, 5, 5, 1]],

         [[5, 9, 9, 5, 1, 7],
          [7, 6, 3, 2, 9, 6],
          [9, 8, 8, 1, 8, 7],
          [4, 8, 1, 2, 9, 7],
          [3, 9, 7, 3, 9, 7]],

         [[8, 8, 5, 4, 6, 2],
          [8, 4, 8, 4, 3, 3],
          [3, 2, 6, 4, 6, 5],
          [7, 8, 7, 5, 2, 9],
          [9, 5, 2, 4, 2, 1]]],


        [[[7, 2, 8, 1, 6, 3],
          [2, 8, 8, 9, 3, 2],
          [7, 7, 7, 4, 9, 5],
          [7, 6, 4, 8, 8, 7],
          [7, 6, 5, 2, 8, 5]],

         [[2, 8, 1, 7, 7, 8],
          [9, 8, 5, 9, 7, 3],
          [3, 6, 3, 1, 8, 9],
          [9, 3, 9, 5, 7, 3],
          [4, 7, 7, 2, 2, 2]],

         [[5, 6, 6, 4, 2, 7],
          [8, 1, 4, 7, 3, 1],
          [4, 1, 3, 8, 9, 

In [59]:
b= np.random.randint(1,10,size=(4,5))

In [60]:
b

array([[1, 4, 4, 4, 3],
       [9, 6, 7, 9, 2],
       [6, 7, 6, 9, 6],
       [3, 5, 5, 6, 9]])

In [61]:
b.sum()

111

In [62]:
b.sum(axis=1)

array([16, 33, 34, 28])

In [68]:
x= np.random.randint(1,10,size=(3,4,5))

In [69]:
x # visyualize it notes in notebook

array([[[9, 2, 5, 1, 3],
        [8, 9, 6, 2, 4],
        [1, 3, 1, 3, 1],
        [7, 8, 4, 8, 9]],

       [[4, 1, 7, 9, 5],
        [5, 4, 6, 6, 9],
        [5, 4, 5, 9, 5],
        [3, 2, 4, 6, 8]],

       [[1, 4, 9, 1, 8],
        [3, 5, 1, 5, 1],
        [1, 2, 2, 9, 2],
        [1, 4, 3, 9, 2]]])

In [66]:
x.sum()

303

In [78]:
# x.sum(axis=1)
x.sum(axis=0)

array([[14,  7, 21, 11, 16],
       [16, 18, 13, 13, 14],
       [ 7,  9,  8, 21,  8],
       [11, 14, 11, 23, 19]])

In [84]:
# np.linspace(1,10,5)  # basically divide 1-10 in 5 equal parts
np.linspace(1,10,11)


array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])